[phases.setup]
nixPkgs = ["nodejs_20", "python311", "python311Packages.pip"]

[phases.install]
cmds = [
  "npm ci",
  "pip install numpy pennylane scikit-learn"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm run db:push && npm start"
